language: node_js
node_js:
  - "8.1.3"

# branches:
#   only:
#     - master

before_script:
  - npm install -g firebase-tools
  - npm install -g preact-cli
  - npm install

script:
  - preact build

after_success:
  # - firebase deploy --token $FIREBASE_TOKEN --non-interactive
  - npm run lh -- https://preact-a6240.firebaseapp.com/ --pwa=100

